### ISSUE TITLE
Analog video is dark and very off center

### ISSUE THREAD

**Issue by amoore2600** [MrX-8B/MiSTer-Arcade-NinjaKun#3]
When using the analog video from RGBS the video is very dark and off center.

**Comment by MrX-8B** [comment]
Thank you for bug report.
I confirmed that it was shifted to the right, but I could not confirm that it was dark.
The black level may be wrong on some monitors due to the shift.
I will fix it in the next release.

**Comment by MrX-8B** [comment]
I couldn't confirm that the screen was dark here, but I fixed it to shift to the right.

**Comment by amoore2600** [comment]
I can confirm the color is no longer dark and and the shift to the right has been corrected using the analog video/RGBS.

**Comment by MrX-8B** [comment]
Thank you!
